name: auto build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
          # cache-dependency-path: '**/pom.xml'
      - name: build with maven
        run: mvn -B clean package --file pom.xml
